-- O que o `drizzle-kit push` criou e nunca virou migracao.
--
-- Descoberto em 12/09/2026, ao criar o PRIMEIRO banco do zero desta base — o
-- da instancia de demonstracao. Ate aqui todo ambiente nasceu de um
-- `drizzle-kit push` contra `shared/schema.ts`, e as migracoes vieram DEPOIS,
-- por cima de um banco que ja tinha tudo. O resultado e que a sequencia de
-- migracoes NUNCA foi capaz de construir um banco que o codigo consiga usar:
-- 25 objetos declarados no schema existiam so em producao, criados pelo push.
--
-- Duas migracoes posteriores ja LIAM objetos desse grupo, entao a sequencia
-- nem chegava ao fim:
--   * 0008_credito_unico.sql             soma `providers.bigdata_credits`
--   * 0015_identificador_de_consulta.sql poe `consulta_id` em
--                                        `bigdata_consultations`
-- As outras 23 nao quebravam migracao alguma — quebrariam em EXECUCAO, que e
-- pior: o Drizzle emite toda coluna declarada em cada `select()`, entao um
-- banco novo derrubaria o login (`users.reset_token`), a busca por endereco
-- (`customers.address_number`) e a Consulta Cadastral inteira.
--
-- O nome `0007b` nao e enfeite: o runner ordena por `.sort()` do nome do
-- arquivo (server/migrate.ts), e "0007_" < "0007b" < "0008". Esta migracao
-- PRECISA correr antes da 0008, onde a falta aparecia primeiro.
--
-- Tudo aqui e idempotente de proposito. Em producao — onde o push ja criou os
-- 25 objetos — esta migracao e registrada e NAO MUDA NADA. Ela existe para o
-- banco novo, e para que a proxima pessoa que criar um ambiente do zero nao
-- repita a investigacao.
--
-- FICARAM DE FORA, de proposito: as 11 tabelas `crm_*` que tambem so existem
-- em producao. Nenhuma delas e declarada em `shared/schema.ts`, entao o app
-- nunca as consulta — nao sao schema deste produto, e recria-las num ambiente
-- novo seria carregar peso morto.
--
-- Os nomes de constraint e indice sao os que o drizzle gerou em producao. Sem
-- isso o Postgres inventaria `..._fkey`, e um diff entre os dois bancos
-- acusaria diferenca onde nao ha.

-- ---------------------------------------------------------------- creditos
-- O bolso da Consulta Cadastral, nas quatro tabelas que o declaram.
ALTER TABLE providers
  ADD COLUMN IF NOT EXISTS bigdata_credits INTEGER NOT NULL DEFAULT 0;
ALTER TABLE credit_orders
  ADD COLUMN IF NOT EXISTS bigdata_credits INTEGER NOT NULL DEFAULT 0;
ALTER TABLE plan_changes
  ADD COLUMN IF NOT EXISTS bigdata_credits_added INTEGER DEFAULT 0;
ALTER TABLE provider_invoices
  ADD COLUMN IF NOT EXISTS bigdata_credits_included INTEGER NOT NULL DEFAULT 0;

-- ------------------------------------------------------------------ acesso
-- Redefinicao de senha e a troca obrigatoria no primeiro acesso.
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS reset_token TEXT;
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS reset_token_expires_at TIMESTAMP;

-- ---------------------------------------------------------------- endereco
-- O endereco fatiado, que a consulta por endereco e o mapa precisam.
ALTER TABLE customers ADD COLUMN IF NOT EXISTS address_number TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS complement     TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS neighborhood   TEXT;

-- ------------------------------------------------------- consulta cadastral
-- Nasce SEM `consulta_id`: quem acrescenta a coluna e o indice unico parcial
-- dela e a 0015, logo adiante. Manter a ordem historica faz o banco novo
-- terminar identico ao de producao, e nao apenas equivalente.
CREATE TABLE IF NOT EXISTS bigdata_consultations (
  id          SERIAL PRIMARY KEY,
  provider_id INTEGER NOT NULL,
  user_id     INTEGER NOT NULL,
  cpf_cnpj    TEXT NOT NULL,
  result      JSONB,
  datasets    TEXT[],
  veredito    TEXT,
  created_at  TIMESTAMP DEFAULT now()
);

CREATE TABLE IF NOT EXISTS bigdata_integrations (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id       INTEGER NOT NULL,
  login             TEXT,
  password          TEXT,
  is_enabled        BOOLEAN NOT NULL DEFAULT false,
  last_check_at     TIMESTAMP,
  last_check_status TEXT,
  created_at        TIMESTAMP DEFAULT now()
);

-- ----------------------------------------------------------- geocodificacao
CREATE TABLE IF NOT EXISTS geo_endereco (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  municipio_ibge  TEXT NOT NULL,
  logradouro_norm TEXT NOT NULL,
  numero          INTEGER,
  cep             TEXT,
  bairro_norm     TEXT,
  latitude        NUMERIC(10,7) NOT NULL,
  longitude       NUMERIC(10,7) NOT NULL
);
CREATE INDEX IF NOT EXISTS geo_endereco_bairro
  ON geo_endereco (municipio_ibge, bairro_norm);
CREATE INDEX IF NOT EXISTS geo_endereco_rua
  ON geo_endereco (municipio_ibge, logradouro_norm, numero);

CREATE TABLE IF NOT EXISTS geo_hps_bairro (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  municipio_ibge TEXT NOT NULL,
  cidade_norm    TEXT NOT NULL,
  uf             TEXT NOT NULL,
  bairro_norm    TEXT NOT NULL,
  fonte          TEXT NOT NULL,
  hps            INTEGER NOT NULL,
  atualizado_em  TIMESTAMP DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS geo_hps_bairro_chave
  ON geo_hps_bairro (municipio_ibge, fonte, bairro_norm);
CREATE INDEX IF NOT EXISTS geo_hps_bairro_cidade
  ON geo_hps_bairro (cidade_norm, uf);

-- ------------------------------------------------- chaves estrangeiras
-- `ADD CONSTRAINT` nao aceita `IF NOT EXISTS`; o guarda por `pg_constraint` e
-- o que torna esta migracao repetivel.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'bigdata_consultations_provider_id_providers_id_fk') THEN
    ALTER TABLE bigdata_consultations
      ADD CONSTRAINT bigdata_consultations_provider_id_providers_id_fk
      FOREIGN KEY (provider_id) REFERENCES providers(id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'bigdata_consultations_user_id_users_id_fk') THEN
    ALTER TABLE bigdata_consultations
      ADD CONSTRAINT bigdata_consultations_user_id_users_id_fk
      FOREIGN KEY (user_id) REFERENCES users(id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'bigdata_integrations_provider_id_providers_id_fk') THEN
    ALTER TABLE bigdata_integrations
      ADD CONSTRAINT bigdata_integrations_provider_id_providers_id_fk
      FOREIGN KEY (provider_id) REFERENCES providers(id);
  END IF;
END $$;
