import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Camera, MapPin, Route, PackageCheck, RefreshCw, AlertTriangle, Clock, X, ArrowRight } from "lucide-react";
import { type FieldCase, type FieldEvent, type FieldVisit, type FieldPoint, visitResults, orderByProximity } from "@shared/recovery-field";
import "./field-operations.css";

const API = "/api/equipment/field";
export async function fieldRequest<T>(path: string, body?: unknown, notifyExpired = true): Promise<T> {
  const response = await fetch(path, { method: body === undefined ? "GET" : "POST", credentials: "include", headers: body === undefined ? undefined : { "Content-Type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) });
  if (!response.ok) { if (response.status === 401 && notifyExpired) window.dispatchEvent(new Event("field:session-expired")); const error = await response.json().catch(() => ({ message: "Não foi possível concluir. Verifique a conexão." })); throw new Error(error.message || "Não foi possível concluir"); }
  return response.json();
}
const money = (v: number) => v.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const date = (v: string | null) => v ? new Date(v).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" }) : "A combinar";
const closed = (c: FieldCase) => !!c.closedAt || ["concluido", "baixado_economico", "prazo_expirado"].includes(c.status);
const stages: Record<string, string> = { pre_recuperacao: "Preparar contato", aguardando_agendamento: "Agendar", agendado: "Visita agendada", nova_tentativa: "Replanejar", concluido: "Recolhido · triagem", contestado: "Em revisão", prazo_expirado: "Prazo encerrado", baixado_economico: "Baixa", devolucao_em_loja: "Entrega em loja", notificacao_formal: "Notificação" };
const nextLabels: Record<string, string> = { reagendar: "Reagendar contato", corrigir_endereco: "Revisar endereço", supervisor: "Revisão do gestor", triagem: "Receber na triagem" };
const technicianAppUrl = import.meta.env.VITE_TECHNICIAN_APP_URL || (import.meta.env.DEV ? "http://127.0.0.1:5001" : null);

function getLocation(): Promise<FieldPoint & { accuracy: number }> {
  return new Promise((resolve, reject) => {
    if (!navigator.geolocation) return reject(new Error("Este dispositivo não disponibiliza GPS"));
    navigator.geolocation.getCurrentPosition(p => resolve({ lat: p.coords.latitude, lng: p.coords.longitude, accuracy: p.coords.accuracy }), () => reject(new Error("Localização indisponível. Autorize o GPS ou informe o motivo.")), { enableHighAccuracy: true, timeout: 15_000, maximumAge: 0 });
  });
}
async function preparePhoto(file: File): Promise<FieldVisit["photos"][number]> {
  if (!["image/jpeg", "image/png", "image/webp"].includes(file.type) || file.size > 12_000_000) throw new Error("Use uma foto JPEG, PNG ou WebP de até 12 MB.");
  const image = await createImageBitmap(file);
  try {
    const scale = Math.min(1, 1200 / Math.max(image.width, image.height));
    const canvas = document.createElement("canvas"); canvas.width = Math.round(image.width * scale); canvas.height = Math.round(image.height * scale);
    const ctx = canvas.getContext("2d"); if (!ctx) throw new Error("Não foi possível preparar a foto");
    ctx.drawImage(image, 0, 0, canvas.width, canvas.height);
    const base64 = canvas.toDataURL("image/jpeg", .65).split(",")[1];
    if (base64.length > 680_000) throw new Error("A foto ainda está grande. Fotografe novamente com menor resolução.");
    return { name: file.name.slice(0, 90).replace(/\.[^.]+$/, "") + ".jpg", mime: "image/jpeg", base64 };
  } finally { image.close(); }
}

export default function FieldOperations({ manager = true }: { manager?: boolean }) {
  const qc = useQueryClient();
  const query = useQuery({ queryKey: [API, "cases", manager ? "management" : "mine"], queryFn: () => fieldRequest<{ cases: FieldCase[]; limit: number }>(`${API}/cases${manager ? "" : "?scope=mine"}`), refetchInterval: 30_000, retry: 1 });
  const team = useQuery({ queryKey: [API, "team"], queryFn: () => fieldRequest<{ id: number; name: string }[]>(`${API}/team`), enabled: manager });
  const [search, setSearch] = useState(""); const [view, setView] = useState("abertos"); const [selected, setSelected] = useState<number[]>([]);
  const [detail, setDetail] = useState<FieldCase | null>(null); const [visiting, setVisiting] = useState(false);
  const [origin, setOrigin] = useState<FieldPoint | null>(null); const [geoError, setGeoError] = useState("");
  const [technician, setTechnician] = useState(""); const [scheduled, setScheduled] = useState("");
  const [plan, setPlan] = useState<ReturnType<typeof orderByProximity> | null>(null); const [notice, setNotice] = useState("");
  const all = query.data?.cases ?? [];
  const open = all.filter(c => !closed(c));
  const visible = useMemo(() => all.filter(c => (view === "encerrados" ? closed(c) : !closed(c)) && [c.customerName, c.city, c.neighborhood, c.serial, c.address].join(" ").toLowerCase().includes(search.toLowerCase())).sort((a, b) => (a.scheduledAt ?? "9999").localeCompare(b.scheduledAt ?? "9999") || (a.route?.order ?? 999) - (b.route?.order ?? 999)), [all, search, view]);
  const stops = selected.flatMap(id => { const c = all.find(c => c.id === id); return c ? [{ caseId: c.id, expectedUpdatedAt: c.updatedAt }] : []; });
  const preview = useMutation({ mutationFn: async () => { if (!origin) throw new Error("Defina o ponto de saída"); return fieldRequest<ReturnType<typeof orderByProximity>>(`${API}/route-preview`, { origin, stops }); }, onSuccess: setPlan });
  const dispatch = useMutation({ mutationFn: async () => {
    if (!origin || !scheduled || !technician || !plan || plan.excluded.length) throw new Error("Revise as paradas, o responsável e a saída antes de distribuir");
    return fieldRequest(`${API}/dispatch`, { origin, stops, assignedToUserId: Number(technician), scheduledAt: new Date(scheduled).toISOString() });
  }, onSuccess: () => { setSelected([]); setPlan(null); setNotice("Rota distribuída. As atividades já estão disponíveis na agenda do responsável."); void qc.invalidateQueries({ queryKey: [API] }); void qc.invalidateQueries({ queryKey: ["/api/equipment/recovery-board"] }); } });
  const events = useQuery({ queryKey: [API, "visits", detail?.id], queryFn: () => fieldRequest<FieldEvent[]>(`${API}/cases/${detail!.id}/visits`), enabled: !!detail });
  const select = (id: number) => { setPlan(null); setSelected(ids => ids.includes(id) ? ids.filter(x => x !== id) : ids.length < 30 ? [...ids, id] : ids); };
  const locate = async () => { setGeoError(""); try { setOrigin(await getLocation()); setPlan(null); } catch (e) { setGeoError((e as Error).message); } };
  return <div className="field-ops">
    <header className="field-hero"><div><span className="field-eyebrow">RECUPERAÇÃO · OPERAÇÃO DE CAMPO</span><h1>{manager ? "Da agenda à devolução." : "Sua agenda de retiradas"}</h1><p>{manager ? "Distribua as visitas, acompanhe as tentativas e confira as evidências em um só lugar." : "Confira cada endereço, registre o que aconteceu e mantenha a equipe informada."}</p></div><button onClick={() => { void query.refetch(); }}><RefreshCw size={16} /> Atualizar</button></header>
    <div className="field-kpis"><div><Clock /><b>{open.length}</b><span>Casos em andamento</span></div><div><Route /><b>{open.filter(c => c.assignedToUserId && c.scheduledAt).length}</b><span>Agendados com responsável</span></div><div><AlertTriangle /><b>{open.filter(c => c.status === "nova_tentativa").length}</b><span>Precisam de nova ação</span></div><div><PackageCheck /><b>{money(all.filter(c => c.status === "concluido").reduce((s, c) => s + Number(c.value || 0), 0))}</b><span>Valor dos recolhidos nesta lista</span></div></div>
    <div className="field-toolbar"><input aria-label="Buscar visita" placeholder="Cliente, bairro, endereço ou série…" value={search} onChange={e => setSearch(e.target.value)} /><select aria-label="Situação das atividades" value={view} onChange={e => setView(e.target.value)}><option value="abertos">Em andamento</option><option value="encerrados">Encerrados</option></select>{manager && (technicianAppUrl ? <a href={technicianAppUrl} target="_blank" rel="noreferrer">Abrir app do técnico ↗</a> : <small>Endereço do app ainda não configurado</small>)}</div>
    {notice && <p className="field-notice" role="status">{notice}</p>}
    {query.isError && <p className="field-error" role="alert">{query.error.message} <button onClick={() => void query.refetch()}>Tentar novamente</button></p>}
    {query.isLoading && <div className="field-skeleton">Carregando a agenda e os equipamentos…</div>}
    {query.data && all.length >= query.data.limit && <p className="field-error">Exibindo os {query.data.limit} casos mais recentes. Há limite de carregamento nesta versão.</p>}
    <div className={`field-layout ${manager ? "" : "field-technician"}`}><section className="field-tasks" aria-label="Atividades de recuperação">
      {!query.isLoading && !visible.length && <div className="field-empty"><PackageCheck size={32} /><h2>Nenhuma atividade neste filtro</h2><p>{manager ? "Abra um caso no kanban para iniciar a recuperação ou revise os filtros." : "As retiradas atribuídas a você aparecerão aqui. Atualize a agenda após a distribuição."}</p></div>}
      {visible.map(c => <article className="field-task" key={c.id} data-testid={`field-case-${c.id}`}><div className="field-task-top">{manager && !closed(c) && <input type="checkbox" checked={selected.includes(c.id)} aria-label={`Selecionar ${c.customerName}`} onChange={() => select(c.id)} />}<span className={`field-stage ${c.status === "nova_tentativa" ? "attention" : ""}`}>{stages[c.status] ?? c.status}</span><span className="field-order">{c.route ? `Parada ${c.route.order}` : `Caso ${c.id}`}</span></div><h2>{c.customerName}</h2><p><MapPin size={14} />{[c.address, c.neighborhood, c.city].filter(Boolean).join(" · ") || "Endereço não informado"}</p><div className="field-asset"><b>{c.equipmentType}</b><span>{c.serial ? `Série ${c.serial}` : c.mac ? `MAC ${c.mac}` : "Identificador pendente"}</span><strong>{c.value ? money(Number(c.value)) : "Valor não informado"}</strong></div><div className="field-meta"><span><Clock size={14} />{date(c.scheduledAt)}</span><span>{c.assignedName ?? "Sem responsável"}</span></div>{(!c.point || !["erp", "endereco"].includes(c.geoPrecision ?? "")) && <p className="field-caution">Localização precisa pendente · fora da ordenação por proximidade</p>}<div className="field-task-actions"><button onClick={() => { setDetail(c); setVisiting(false); }}>Detalhes e evidências <ArrowRight size={14} /></button>{!closed(c) && c.status !== "contestado" && <button className="field-primary" onClick={() => { setDetail(c); setVisiting(true); }}><Camera size={15} /> Registrar visita</button>}</div></article>)}
    </section>{manager && <aside className="field-planner"><span className="field-eyebrow">PLANEJAR ROTA</span><h2>{selected.length} de até 30 paradas</h2><p>Selecione os casos da mesma região. A proximidade sugere a sequência; confirme os horários com os clientes.</p><label>Responsável<select value={technician} onChange={e => setTechnician(e.target.value)}><option value="">Selecione o responsável</option>{team.data?.map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</select></label>{team.isError && <p className="field-error">Não foi possível carregar a equipe.</p>}<label>Saída prevista<input type="datetime-local" value={scheduled} onChange={e => setScheduled(e.target.value)} /></label><button onClick={() => void locate()}><MapPin size={16} /> Usar minha localização como saída</button><div className="field-coordinates"><label>Latitude<input type="number" step="any" value={origin?.lat ?? ""} onChange={e => { setOrigin({ lat: Number(e.target.value), lng: origin?.lng ?? 0 }); setPlan(null); }} /></label><label>Longitude<input type="number" step="any" value={origin?.lng ?? ""} onChange={e => { setOrigin({ lat: origin?.lat ?? 0, lng: Number(e.target.value) }); setPlan(null); }} /></label></div>{geoError && <p className="field-error">{geoError}</p>}<button disabled={!selected.length || !origin || preview.isPending} onClick={() => preview.mutate()}><Route size={16} /> Ordenar por proximidade</button>{preview.error && <p className="field-error">{preview.error.message}</p>}{plan && <div className="field-route"><b>{plan.distanceKm.toFixed(1)} km em linha reta</b><small>Não inclui trânsito, ruas, tempo de visita ou retorno.</small><ol>{plan.stops.map(s => <li key={s.caseId}>{all.find(c => c.id === s.caseId)?.customerName}<span>{s.distanceKm.toFixed(1)} km</span></li>)}</ol>{plan.excluded.length > 0 && <p className="field-error">{plan.excluded.length} caso(s) sem localização precisa. Retire da seleção antes de distribuir.</p>}</div>}<button className="field-primary" disabled={!plan || !!plan.excluded.length || !technician || !scheduled || dispatch.isPending} onClick={() => dispatch.mutate()}>{dispatch.isPending ? "Distribuindo…" : "Distribuir para o responsável"}</button>{dispatch.error && <p className="field-error" role="alert">{dispatch.error.message}</p>}<p className="field-private">Fotos e localização ficam restritas ao seu provedor.</p></aside>}</div>
    {detail && <FieldDialog onClose={() => { if (!visiting || window.confirm("Sair sem salvar este registro de visita?")) setDetail(null); }}><header><div><h2 id="field-detail-title">{visiting ? "Registrar visita" : "Detalhes da atividade"}</h2><p>{detail.customerName} · {detail.equipmentType}</p></div><button aria-label="Fechar detalhes" onClick={() => { if (!visiting || window.confirm("Sair sem salvar este registro de visita?")) setDetail(null); }}><X /></button></header>{visiting ? <VisitForm key={detail.id} item={detail} onSaved={() => { setVisiting(false); setDetail(null); setNotice("Visita registrada com evidências. A equipe já pode acompanhar o resultado."); void qc.invalidateQueries({ queryKey: [API] }); void qc.invalidateQueries({ queryKey: ["/api/equipment/recovery-board"] }); }} /> : <div className="field-modal-body"><dl><dt>Endereço</dt><dd>{[detail.address, detail.neighborhood, detail.city].filter(Boolean).join(" · ") || "Não informado"}</dd><dt>Telefone</dt><dd>{detail.phone ? <a href={`tel:${detail.phone.replace(/[^+0-9]/g, "")}`}>{detail.phone}</a> : "Não informado"}</dd><dt>Equipamento</dt><dd>{detail.equipmentType} · Série {detail.serial ?? "—"} · MAC {detail.mac ?? "—"} · Patrimônio {detail.assetTag ?? "—"}</dd><dt>Responsável e agenda</dt><dd>{detail.assignedName ?? "Não atribuído"} · {date(detail.scheduledAt)}</dd></dl>{detail.address && <a className="field-navigation" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent([detail.address, detail.city].filter(Boolean).join(", "))}`}>Abrir navegação para o endereço ↗</a>}<h3>Histórico de visitas</h3>{events.isLoading && <p>Carregando evidências…</p>}{events.isError && <p className="field-error">Não foi possível carregar o histórico.</p>}{events.data?.length === 0 && <p>Nenhuma visita com evidências registrada.</p>}{events.data?.map(event => <article className="field-event" key={event.id}><strong>{visitResults[event.result] ?? event.result}</strong><small>{date(event.occurredAt)} · {event.technician ?? "Responsável não informado"}</small><p>{event.notes}</p><p>Próximo passo: {nextLabels[event.nextAction] ?? event.nextAction}</p><small>{event.location ? `GPS: ${event.location.lat.toFixed(5)}, ${event.location.lng.toFixed(5)} · precisão ±${Math.round(event.location.accuracy)} m (informada pelo dispositivo)` : `Sem GPS: ${event.locationReason}`}</small><div className="field-photos">{event.photos.map(photo => <a key={photo.url} href={photo.url} target="_blank" rel="noreferrer"><img src={photo.url} alt={photo.name} loading="lazy" /></a>)}</div></article>)}</div>}</FieldDialog>}
  </div>;
}

function VisitForm({ item, onSaved }: { item: FieldCase; onSaved: () => void }) {
  const [requestId] = useState(() => crypto.randomUUID()); const [occurredAt] = useState(() => new Date().toISOString());
  const [result, setResult] = useState<FieldVisit["result"]>("cliente_ausente"); const [notes, setNotes] = useState("");
  const [location, setLocation] = useState<FieldVisit["location"]>(null); const [locationReason, setLocationReason] = useState("");
  const [photos, setPhotos] = useState<FieldVisit["photos"]>([]); const [identifier, setIdentifier] = useState("");
  const [nextAction, setNextAction] = useState<FieldVisit["nextAction"]>("reagendar"); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const mutation = useMutation({ mutationFn: () => fieldRequest(`${API}/cases/${item.id}/visits`, { requestId, occurredAt, expectedUpdatedAt: item.updatedAt, result, notes, location, locationReason: location ? undefined : locationReason, photos, collectedIdentifier: result === "recolhido" ? identifier : undefined, nextAction }), onSuccess: onSaved });
  const locate = async () => { setError(""); setBusy(true); try { setLocation(await getLocation()); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  const attach = async (files: FileList | null) => { if (!files?.length) return; setError(""); setBusy(true); try { if (photos.length + files.length > 3) throw new Error("Limite de três fotos por visita"); const prepared = await Promise.all(Array.from(files).map(preparePhoto)); setPhotos(p => [...p, ...prepared]); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  return <form className="field-modal-body field-visit-form" onSubmit={e => { e.preventDefault(); mutation.mutate(); }}><p className="field-notice">Registre apenas o necessário para documentar a visita. Evite fotografar pessoas e documentos.</p><fieldset disabled={mutation.isPending}><label>O que aconteceu?<select value={result} onChange={e => { const r = e.target.value as FieldVisit["result"]; setResult(r); setNextAction(r === "recolhido" ? "triagem" : "reagendar"); }}>{Object.entries(visitResults).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label>{result === "recolhido" && <label>Série, MAC ou patrimônio do aparelho recolhido<input required value={identifier} onChange={e => setIdentifier(e.target.value)} placeholder="Confira a etiqueta do aparelho" /><small>A identificação deve corresponder ao equipamento desta atividade.</small></label>}<label>Relato da visita<textarea required minLength={12} maxLength={2000} value={notes} onChange={e => setNotes(e.target.value)} placeholder="Ex.: compareci ao endereço e toquei a campainha. Não houve atendimento." /></label><label>Próxima ação<select value={nextAction} onChange={e => setNextAction(e.target.value as FieldVisit["nextAction"])}>{Object.entries(nextLabels).filter(([id]) => result === "recolhido" ? id === "triagem" : id !== "triagem").map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><button type="button" onClick={() => void locate()} disabled={busy}><MapPin size={16} /> Capturar localização da visita</button>{location ? <p>GPS registrado · precisão informada de ±{Math.round(location.accuracy)} m.</p> : <label>Se o GPS estiver indisponível, informe o motivo<input required minLength={10} value={locationReason} onChange={e => setLocationReason(e.target.value)} /></label>}<label className="field-photo-input"><Camera size={20} /> Evidências · {photos.length}/3 fotos<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" multiple disabled={busy || photos.length >= 3} onChange={e => { void attach(e.target.files); e.target.value = ""; }} /></label><div className="field-photos">{photos.map((p, i) => <div key={i}><img src={`data:${p.mime};base64,${p.base64}`} alt={`Foto da visita ${i + 1}`} /><button type="button" onClick={() => setPhotos(list => list.filter((_, ix) => ix !== i))}>Remover foto {i + 1}</button></div>)}</div></fieldset>{error && <p className="field-error" role="alert">{error}</p>}{mutation.error && <p className="field-error" role="alert">{mutation.error.message} O formulário permanece preenchido para tentar novamente.</p>}<button className="field-primary" type="submit" disabled={busy || mutation.isPending || !photos.length}>{mutation.isPending ? "Enviando evidências…" : "Salvar visita e atualizar atividade"}</button><small>Confirme o envio antes de fechar. Sem conexão, mantenha esta tela aberta para tentar novamente.</small></form>;
}

function FieldDialog({ children, onClose }: { children: ReactNode; onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const dialog = ref.current; dialog?.showModal(); return () => dialog?.close(); }, []);
  return <dialog ref={ref} className="field-modal" aria-labelledby="field-detail-title" onCancel={e => { e.preventDefault(); onClose(); }}>{children}</dialog>;
}
