import { pgTable,integer,serial,bigserial,text,jsonb,timestamp,date,boolean,uniqueIndex,index,check } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { providers,customers,invoices,users } from './schema';
export const cobrancaGestaoConfig=pgTable('cobranca_gestao_config',{
 providerId:integer('provider_id').primaryKey().references(()=>providers.id),config:jsonb('config').notNull().default({}),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow(),
});
export const cobrancaContestacoes=pgTable('cobranca_contestacoes',{
 id:serial('id').primaryKey(),providerId:integer('provider_id').notNull().references(()=>providers.id),customerId:integer('customer_id').notNull().references(()=>customers.id),faturaId:integer('fatura_id').notNull().references(()=>invoices.id),
 motivo:text('motivo').notNull(),relato:text('relato').notNull(),evidencia:text('evidencia').notNull().default(''),responsavelId:integer('responsavel_id').notNull().references(()=>users.id),prazo:date('prazo').notNull(),status:text('status').notNull().default('aberta'),
 criadoPor:integer('criado_por').notNull().references(()=>users.id),criadoEm:timestamp('criado_em',{withTimezone:true}).notNull().defaultNow(),resolvidoPor:integer('resolvido_por').references(()=>users.id),resolvidoEm:timestamp('resolvido_em',{withTimezone:true}),justificativa:text('justificativa'),
},t=>[uniqueIndex('cobranca_contestacao_aberta').on(t.providerId,t.faturaId).where(sql`${t.status}='aberta'`),index('cobranca_contestacao_cliente').on(t.providerId,t.customerId,t.status),check('cobranca_contestacoes_motivo_check',sql`${t.motivo} IN ('valor','pagamento','servico','duplicidade','titularidade','outro')`),check('cobranca_contestacoes_status_check',sql`${t.status} IN ('aberta','procedente','improcedente','cancelada')`),check('cobranca_contestacoes_check',sql`(${t.status}='aberta' AND ${t.resolvidoEm} IS NULL) OR (${t.status}<>'aberta' AND ${t.resolvidoEm} IS NOT NULL AND ${t.resolvidoPor} IS NOT NULL AND ${t.justificativa} IS NOT NULL)`)]);
export const cobrancaContatosOrcamento=pgTable('cobranca_contatos_orcamento',{
 id:bigserial('id',{mode:'number'}).primaryKey(),providerId:integer('provider_id').notNull().references(()=>providers.id),customerId:integer('customer_id').notNull().references(()=>customers.id),canal:text('canal').notNull(),automatico:boolean('automatico').notNull(),chave:text('chave').notNull(),status:text('status').notNull().default('reservado'),criadoEm:timestamp('criado_em',{withTimezone:true}).notNull().defaultNow(),atualizadoEm:timestamp('atualizado_em',{withTimezone:true}).notNull().defaultNow(),
},t=>[uniqueIndex('cobranca_contatos_orcamento_provider_id_chave_key').on(t.providerId,t.chave),index('cobranca_orcamento_cliente').on(t.providerId,t.customerId,t.criadoEm.desc()),check('cobranca_contatos_orcamento_canal_check',sql`${t.canal} IN ('whatsapp','sms','email')`),check('cobranca_contatos_orcamento_status_check',sql`${t.status} IN ('reservado','enviado','falhou','incerto')`)]);
